[ ERROR ] Error in file '/home/runner/work/robot-applitools-tests/robot-applitools-tests/resources/common_keywords.robot' on line 4: Importing library '../resources/common_variables.robot' failed: ModuleNotFoundError: No module named '.'
Traceback (most recent call last):
  None
PYTHONPATH:
  /opt/hostedtoolcache/Python/3.8.18/x64/bin
  /opt/hostedtoolcache/Python/3.8.18/x64/lib/python38.zip
  /opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8
  /opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/lib-dynload
  /opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages
(node:1864) ExperimentalWarning: Module._stat is an experimental feature and might change at any time
(Use `core --trace-warnings ...` to show where the warning was created)
(node:1864) ExperimentalWarning: Module._readPackage is an experimental feature and might change at any time
[ ERROR ] Re-raising an error received from SDK server: USDKFailure('Request "getAccountInfo" [0--cc57a96f-fcd5-4648-8160-4c6084163466] that was sent to the address "[GET]https://eyesapi.applitools.com/api/sessions/renderinfo?apiKey=%3Capi-key%3E" failed due to unexpected status Unauthorized(401)', '    at Object.afterResponse (/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/applitools/core_universal/bin/core/__sea/node_modules/@applitools/core-base/dist/server/req-eyes.js:104:23)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async /opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/applitools/core_universal/bin/core/__sea/node_modules/@applitools/req/dist/index.cjs:9828:20\n    at async req2 (/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/applitools/core_universal/bin/core/__sea/node_modules/@applitools/req/dist/index.cjs:9729:18)\n    at async req (/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/applitools/core_universal/bin/core/__sea/node_modules/@applitools/req/dist/index.cjs:9640:12)\n    at async getAccountInfo (/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/applitools/core_universal/bin/core/__sea/node_modules/@applitools/core-base/dist/server/requests.js:340:26)\n    at async Object.getAccountInfo (/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/applitools/core_universal/bin/core/__sea/node_modules/@applitools/core-base/dist/get-account-info.js:34:25)\n    at async Object.openEyes (/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/applitools/core_universal/bin/core/__sea/dist/ufg/open-eyes.js:56:25)\n    at async getTypedEyes (/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/applitools/core_universal/bin/core/__sea/dist/get-typed-eyes.js:9:20)\n    at async openEyes (/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/applitools/core_universal/bin/core/__sea/dist/open-eyes.js:97:22)')
Unhandled promise rejection Error: Request "logEvent" [0--efc017d9-7c07-4e92-a9c0-c68332cfd371] that was sent to the address "[POST]https://eyesapi.applitools.com/api/sessions/log?apiKey=%3Capi-key%3E" failed due to unexpected status Unauthorized(401)
    at Object.afterResponse (/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/applitools/core_universal/bin/core/__sea/node_modules/@applitools/core-base/dist/server/req-eyes.js:104:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/applitools/core_universal/bin/core/__sea/node_modules/@applitools/req/dist/index.cjs:9828:20
    at async req2 (/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/applitools/core_universal/bin/core/__sea/node_modules/@applitools/req/dist/index.cjs:9729:18)
    at async req (/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/applitools/core_universal/bin/core/__sea/node_modules/@applitools/req/dist/index.cjs:9640:12)
    at async Object.logEvent (/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/applitools/core_universal/bin/core/__sea/node_modules/@applitools/core-base/dist/server/requests.js:422:9)
